# Generated by Django 5.1.4 on 2025-02-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='valve',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
