# Generated by Django 5.1.4 on 2025-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='valve_close_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
