# Generated by Django 5.1.4 on 2025-01-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alter_sensordata_valve_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valve',
            name='valve_no',
            field=models.IntegerField(choices=[(1, 'Valve 1'), (2, 'Valve 2')], error_messages={'invalid_choice': 'Valve number must be either 1 or 2'}),
        ),
    ]
