# Generated by Django 5.1.4 on 2025-02-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_valve_valve_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValveControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('valve_no', models.IntegerField(choices=[(1, 'Valve 1'), (2, 'Valve 2')], default=1, error_messages={'invalid_choice': 'Valve number must be either 1 or 2'})),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
